language: php
php:
  - '7.0'
  - '7.1'
before_script:
  - cd /home/travis/build/bang-dai/sf3-devops
  - composer install
script:
  - vendor/bin/behat
  - vendor/bin/simple-phpunit
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "sf3-devops"
    skip_cleanup: true
    region: eu-west-2
    on:
      branch: staging
    # rest of S3 deployment for MyApp.zip
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "sf3-devops"
    key: latest/MyApp.zip
    application: sf3-devops
    deployment_group: sf3-devops
    region: eu-west-2
    on:
      branch: staging
after_deploy:
  - echo "Deploy with success"